export type RadialProgressProps = {
    size?: number,
    // strokeWidth?: number,
    colorCircle?: boolean,
    colorSlice?: string,
    fontColor?: string,
    fontSize?: string,
    fontWeight?: number,
    lineargradient?: string[],
    number?: boolean,
    round?: boolean,
    fill?: string,
    unit?: string,
    rotation?: number,
    stroke?: number,
    index?: number,
    inverse?: boolean,
    percent?: number,
}